language: php
php:
  - 7.2
  - 7.3
  - 7.4

# Cache composer packages so "composer install" is faster
cache:
 directories:
   - $HOME/.composer/cache/files

before_script:
  - composer self-update
  - composer install
  - composer dump-autoload -o

script:
  - ./vendor/bin/phpunit --bootstrap vendor/autoload.php tests/
